# Generated by Django 3.2.2 on 2021-05-13 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.UUIDField(default=uuid.uuid4)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('product_unit_price', models.FloatField(default=0.0)),
                ('current_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('purchase_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supershop_app.user')),
                ('purchased_products', models.ManyToManyField(to='supershop_app.Product')),
            ],
        ),
    ]
