# Generated by Django 3.2.2 on 2021-05-16 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('order_placed', models.BooleanField(default=False)),
                ('purchase_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchased_products', models.ManyToManyField(to='supershop_app.Product')),
            ],
        ),
    ]
