# Generated by Django 3.2.2 on 2021-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_products',
            field=models.ManyToManyField(db_constraint=False, to='supershop_app.Product'),
        ),
    ]
