# Generated by Django 3.2.2 on 2021-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0003_auto_20210517_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
