# Generated by Django 3.2.2 on 2021-05-16 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0004_product_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.UUIDField(default=uuid.uuid4)),
                ('order', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supershop_app.order')),
                ('product', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supershop_app.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='purchased_products',
            field=models.ManyToManyField(through='supershop_app.Cart', to='supershop_app.Product'),
        ),
    ]
