# Generated by Django 3.2.2 on 2021-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0004_auto_20210514_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
