# Generated by Django 3.2.2 on 2021-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0005_alter_order_purchased_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_price',
            field=models.FloatField(default=0),
        ),
    ]
