# Generated by Django 3.2.2 on 2021-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0005_alter_productcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
