# Generated by Django 3.2.2 on 2021-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0006_auto_20210521_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
