# Generated by Django 3.2.2 on 2021-05-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
