# Generated by Django 3.2.2 on 2021-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop_app', '0009_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
